name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5.3.0
        with:
          context: note_app
          file: note_app/Dockerfile
          push: true
          build-args: |
            NODE_ENV=production
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/note-app:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/note-app:cache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/note-app:cache,mode=max
