name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: note_app
          file: note_app/Dockerfile
          push: true
          build-args: |
            NODE_ENV=production
            MONGODB_URI=${{ secrets.MONGODB_URI }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/note-app:latest
